##
# Bạn nên tham khảo các URL sau để nắm vững kiến thức về
# các file cấu hình Nginx nhằm khai thác tối đa sức mạnh của Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# Trong hầu hết trường hợp, quản trị viên sẽ xóa file này khỏi sites-enabled/ và
# giữ nó làm file tham khảo bên trong sites-available, nơi nó sẽ tiếp tục được
# cập nhật bởi đội ngũ đóng gói Nginx.
#
# File này sẽ tự động tải các file cấu hình được cung cấp bởi các
# ứng dụng khác, chẳng hạn như Drupal hoặc Wordpress. Các ứng dụng này sẽ
# khả dụng bên dưới một đường dẫn có tên gói đó, ví dụ: /drupal8.
#
# Vui lòng xem /usr/share/doc/nginx-doc/examples/ để biết các ví dụ chi tiết hơn.
##

# Cấu hình server mặc định
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Cấu hình SSL
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Lưu ý: Bạn nên tắt gzip cho lưu lượng truy cập SSL.
        # Xem: https://bugs.debian.org/773332
        #
        # Tìm hiểu về ssl_ciphers để đảm bảo cấu hình bảo mật.
        # Xem: https://bugs.debian.org/765782
        #
        # Chứng chỉ tự ký (Self-signed) được tạo bởi gói ssl-cert
        # Không sử dụng chúng trên server môi trường thực tế (production)!
        #
        # include snippets/snakeoil.conf;
        #
        # ssl_certificate /etc/nginx/ssl/file.crt;
        # ssl_certificate_key /etc/nginx/ssl/file.key;

        root /var/www/html;

        # Thêm index.php vào danh sách nếu bạn đang sử dụng PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # Đầu tiên thử trả về yêu cầu dưới dạng file, nếu không được thì
                # thử dạng thư mục, nếu vẫn không được thì chuyển về hiển thị lỗi 404.
                try_files $uri $uri/ =404;
        }

        # Chuyển các script PHP sang cho FastCGI server xử lý
        #
        #location ~ \.php$ {
        #        include snippets/fastcgi-php.conf;
        #
        #        # Dùng với php-fpm (hoặc các unix socket khác):
        #        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #        # Dùng với php-cgi (hoặc các tcp socket khác):
        #        fastcgi_pass 127.0.0.1:9000;
        #}

        # Chặn truy cập vào các file .htaccess, nếu thư mục gốc của Apache
        # trùng với thư mục gốc của Nginx
        #
        #location ~ /\.ht {
        #        deny all;
        #}
}


# Cấu hình Virtual Host cho trang example.com
#
# Bạn có thể chuyển cấu hình này sang một file riêng trong sites-available/ và tạo link liên kết (symlink)
# sang sites-enabled/ để kích hoạt nó.
#
#server {
#        listen 80;
#        listen [::]:80;
#
#        server_name example.com;
#
#        root /var/www/example.com;
#        index index.html;
#
#        location / {
#                try_files $uri $uri/ =404;
#        }
#}