server {
        listen 80;
        listen [::]:80;
        server_name grafana.nathan-vo.com;
        return 301  https://$host$request_uri;
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name grafana.nathan-vo.com;

        ssl_certificate /etc/nginx/ssl/nathan-vo.com.crt;
        ssl_certificate_key /etc/nginx/ssl/nathan-vo.com.key;

        location / {
                proxy_pass  http://0.0.0.0:3000;
                include proxy_params;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}
